
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: JSHacks
email: contact@jshacks.io
description: > # this means to ignore newlines until "baseurl:"
  JS Hacks consists of a series of hackathons that bring together JavaScript enthusiasts to build innovative solutions that solve real-world problems.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jshacks.io" # the base hostname & protocol for your site
twitter_username: jshacksio
github_username: js-hacks
facebook_username: jshacks

# Build settings
markdown: kramdown

google_analytics: UA-84490590-1